# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('score', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='attendees',
            field=models.ManyToManyField(related_name='attended', to='movienite.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='picker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked', to='movienite.Person'),
        ),
    ]
