# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movienite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='attendees',
            field=models.ManyToManyField(related_name='movies_attended', to='movienite.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_picked', to='movienite.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='score',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
