# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movienite', '0002_auto_20171007_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-score', 'name']},
        ),
    ]
